name: Update Main with Latest Release

on:
  release:
    types: [published]

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all tags and branches
      run: |
        git fetch --all

    - name: Merge latest release into main
      run: |
        git checkout main
        git merge --ff-only $(git describe --tags `git rev-list --tags --max-count=1`)
        git push origin main
